In [1]:
from Util import *

In [2]:
X, y = make_data(1000, 60, 5)
train_X, val_X, test_X, train_y, val_y, test_y = preprocess(X, y, False)


[ 0. 60.  0.]
[ 0. 60.  0.]
[ 0. 60.  0.]
[ 0. 60.  0.]
[ 0. 60.  0.]
[ 0. 60.  0.]
[ 8. 52.  0.]
[60.  0.  0.]
[60.  0.  0.]
[60.  0.  0.]
[60.  0.  0.]
[60.  0.  0.]
[60.  0.  0.]
[60.  0.  0.]
[60.  0.  0.]
[60.  0.  0.]


In [3]:
print(y)

[1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
net = NN3([1, 3, 5, 7], [200, 1], 3703, 1, 12, 1)

In [5]:
net.train_model(train_X, train_y)

RuntimeError: Input and parameter tensors are not at the same device, found input tensor at cuda:0 and parameter tensor at cpu

In [ ]:
torch.unsqueeze(train_X[0], 1).flatten(1).unsqueeze(0).shape


torch.Size([1, 12, 40000])

In [ ]:
x = train_X[0]
x.shape

torch.Size([12, 200, 200])

In [ ]:
x = x.view(len(x), 1, -1)
print(x)

tensor([[[ 19.,  20.,  16.,  ..., 137., 138., 138.]],

        [[ 19.,  16.,  17.,  ..., 138., 138., 137.]],

        [[ 23.,  19.,  17.,  ..., 137., 137., 138.]],

        ...,

        [[ 21.,  19.,  17.,  ..., 137., 138., 138.]],

        [[ 18.,  16.,  17.,  ..., 137., 138., 138.]],

        [[ 21.,  18.,  17.,  ..., 138., 137., 138.]]], device='cuda:0',
       dtype=torch.float16)
